services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=vaadinstart'
      - 'POSTGRES_PASSWORD=vaadinstart'
      - 'POSTGRES_USER=vaadinstart'
    ports:
      - '5432:5432'
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg-data:
